# Generated by Django 4.2.3 on 2023-07-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorvete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(choices=[('Aç', 'Açai'), ('Cup', 'Cupuaçu')], default='Aç', max_length=3)),
                ('cobertura', models.CharField(choices=[('cho', 'Chocolate'), ('mor', 'Morango'), ('car', 'Caramelo'), ('leC', 'Leite condensado')], default='leC', max_length=3)),
                ('tamanho', models.CharField(choices=[('peq', 'Pequeno'), ('med', 'Médio'), ('grd', 'Grande'), ('brc', 'Barca')], default='med', max_length=3)),
            ],
        ),
    ]
